const { parentPort, workerData } = require('worker_threads');
const mongoose = require('mongoose');
const { findSimilarFragments } = require('../services/search.service');
const { Fragment, Link } = require('../models');
const logger = require('../utils/logger');

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI, {
  useNewUrlParser: true,
  useUnifiedTopology: true,
});

// Minimum similarity score to create a link
const MIN_SIMILARITY_SCORE = 0.7;

/**
 * Find and create links for similar fragments
 * @param {string} fragmentId - The fragment ID to find similar fragments for
 * @param {string} userId - The user ID who owns the fragment
 * @returns {Promise<Object>} Results of the linking process
 */
async function processLinks(fragmentId, userId) {
  try {
    logger.info(`Finding similar fragments for: ${fragmentId}`);
    
  // Get the source fragment (include embedding - schema has select: false)
  const sourceFragment = await Fragment.findOne({ _id: fragmentId, user: userId }).select('+embedding');
    if (!sourceFragment) {
      throw new Error(`Fragment not found: ${fragmentId}`);
    }
    
    if (!sourceFragment.embedding) {
      logger.warn(`No embedding found for fragment: ${fragmentId}`);
      return { success: true, fragmentId, linksCreated: 0 };
    }
    
    // Find similar fragments (excluding itself and already linked fragments)
    const existingLinks = await Link.find({
      $or: [
        { sourceFragment: fragmentId },
        { targetFragment: fragmentId },
      ],
    });
    
    const linkedFragmentIds = [
      ...new Set(
        existingLinks.flatMap(link => [
          link.sourceFragment.toString(),
          link.targetFragment.toString(),
        ])
      ),
    ];
    
    // Find similar fragments that aren't already linked
    const similarFragments = await findSimilarFragments(
      sourceFragment.embedding,
      { 
        _id: { 
          $ne: sourceFragment._id,
          $nin: linkedFragmentIds,
        },
        user: userId,
      },
      { minScore: MIN_SIMILARITY_SCORE, limit: 10 }
    );
    
    // Create links for similar fragments
    const linkPromises = similarFragments.map(async (fragment) => {
      // Check if link already exists in either direction
      const existingLink = await Link.findOne({
        $or: [
          { sourceFragment: fragmentId, targetFragment: fragment._id },
          { sourceFragment: fragment._id, targetFragment: fragmentId },
        ],
      });
      
      if (!existingLink) {
        return Link.create({
          sourceFragment: fragmentId,
          targetFragment: fragment._id,
          type: 'related',
          user: userId,
          score: fragment.score,
          metadata: {
            autoGenerated: true,
            algorithm: 'cosine_similarity',
          },
        });
      }
      return null;
    });
    
    const results = await Promise.all(linkPromises);
    const createdLinks = results.filter(link => link !== null);
    
    logger.info(`Created ${createdLinks.length} links for fragment: ${fragmentId}`);
    
    return {
      success: true,
      fragmentId,
      linksCreated: createdLinks.length,
      links: createdLinks,
    };
  } catch (error) {
    logger.error(`Error processing links for fragment ${fragmentId}:`, error);
    return {
      success: false,
      fragmentId,
      error: error.message,
    };
  }
}

// Handle messages from the main thread
parentPort.on('message', async (message) => {
  if (message.type === 'process') {
    const { fragmentId, userId } = message.data;
    const result = await processLinks(fragmentId, userId);
    parentPort.postMessage({ type: 'complete', data: result });
  }
});

// Handle uncaught exceptions
process.on('uncaughtException', (error) => {
  logger.error('Uncaught exception in link worker:', error);
  process.exit(1);
});

// Handle unhandled promise rejections
process.on('unhandledRejection', (reason, promise) => {
  logger.error('Unhandled Rejection at:', promise, 'reason:', reason);
});

// For testing with worker_threads
if (workerData) {
  const { fragmentId, userId } = workerData;
  processLinks(fragmentId, userId)
    .then((result) => {
      if (parentPort) {
        parentPort.postMessage({ type: 'complete', data: result });
      }
    })
    .catch((error) => {
      if (parentPort) {
        parentPort.postMessage({ type: 'error', error: error.message });
      }
    });
}
